# Generated by Django 5.2.1 on 2025-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio')),
                ('modelo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Modelo')),
                ('kilometraje', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Kilometraje')),
                ('lugar_de_venta', models.TextField(blank=True, null=True, verbose_name='Lugar de Venta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'db_table': 'articulos',
            },
        ),
    ]
