# Generated by Django 5.2.1 on 2025-05-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio')),
                ('modelo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Modelo')),
                ('kilometraje', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Kilometraje')),
                ('lugar_de_venta', models.TextField(blank=True, null=True, verbose_name='Lugar de Venta')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('tipo_combustible', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Combustible')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'db_table': 'articulos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('user', models.CharField(max_length=150, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('fk_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
    ]
