# Generated by Django 5.2.1 on 2025-05-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='tipo_combustible',
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Color'),
        ),
    ]
