# Generated by Django 5.2.1 on 2025-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_remove_articulo_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Color'),
        ),
    ]
