# Generated by Django 5.2.1 on 2025-05-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_alter_articulo_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_modificacion',
        ),
    ]
