# Generated by Django 5.2.1 on 2025-05-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_alter_articulo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='tienda',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tienda'),
        ),
    ]
