# Generated by Django 5.2.1 on 2025-05-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_articulo_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='marca',
        ),
    ]
